ex 11.19 - test 2 (fails)

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -37,6 +37,10 @@ jobs:
           node-version: "24"
           cache: "npm"
 
+      # simulation failure
+      - name: Force failure test
+        run: exit 1
+
       - name: Install dependencies
         run: npm install
 
